# Generated by Django 6.0.4 on 2026-05-17 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answer_created_at_alter_answer_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=20000, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=20000, verbose_name='Текст вопроса'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['id'], name='question_active_idx'),
        ),
    ]
