# Generated by Django 6.0.4 on 2026-05-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_answer_text_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактировано'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактировано'),
        ),
    ]
